version: '3.8'

services:
  app:
    image: your-app-image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: sswwee
      MYSQL_USER: melkmeshi
      MYSQL_ROOT_PASSWORD: MohElk13241
      MYSQL_PASSWORD: MohElk13241
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
